FROM microsoft/dotnet:2.1-sdk AS base
WORKDIR /src
COPY LBHAsbestosAPI.sln ./
COPY LBHAsbestosAPI/LBHAsbestosAPI.csproj LBHAsbestosAPI/
RUN dotnet restore -nowarn:msb3202,nu1503
COPY . .
WORKDIR /src/LBHAsbestosAPI
RUN dotnet build LBHAsbestosAPI.csproj -c Release -o /app
