using System;
namespace LBHAsbestosAPI.Entities
{
	public class Inspection
	{
        public int Id { get; set; }
        public int JobId { get; set; }
        public string PriorityAssessmentScore { get; set; }
        public string LocationDescription { get; set; }
        public string Quantity { get; set; }
        public int FloorId { get; set; }
        public int RoomId { get; set; }
        public int ElementId { get; set; }
        public string Material { get; set; }
        public string MaterialScore { get; set; }
        public string MaterialType { get; set; }
        public string MaterialTypeScore { get; set; }
        public string Measurement { get; set; }
        public string Position { get; set; }
        public string PositionScore { get; set; }
        public string Friability { get; set; }
        public string FriabilityScore { get; set; }
        public string Access { get; set; }
        public string AccessScore { get; set; }
        public string PhotoId { get; set; }
        public string DrawingId { get; set; }
        public string Condition { get; set; }
        public string ConditionScore { get; set; }
        public int? InspectionNumber { get; set; }
        public string InspectionType { get; set; }
        public int? InspectionTypeScore { get; set; }
        public string Protection { get; set; }
        public string ProtectionScore { get; set; }
        public string InspectionResult { get; set; }
        public int? InspectionResultScore { get; set; }
        public int? InspectionScore { get; set; }
        public int? MaterialAssessmentScore { get; set; }
        public string InspectionScoreCategory { get; set; }
        public string QuantityLeft { get; set; }
        public DateTime DateOfInspection { get; set; }
        public string InspectedBy { get; set; }
        public int PropertyId { get; set; }
        public string Field1 { get; set; }
        public string Field1Score { get; set; }
        public string Field2 { get; set; }
        public string Field2Score { get; set; }
        public string Field3 { get; set; }
        public string Field3Score { get; set; }
        public string Field4 { get; set; }
        public string Field4Score { get; set; }
        public string Field5 { get; set; }
        public string Field5Score { get; set; }
        public string Field6 { get; set; }
        public string Field6Score { get; set; }
        public string Field7 { get; set; }
        public string Field7Score { get; set; }
        public string Field8 { get; set; }
        public string Field8Score { get; set; }
        public string Field9 { get; set; }
        public string Field9Score { get; set; }
        public string Text1 { get; set; }
        public string DtmDate1 { get; set; }
        public string Comment { get; set; }
        public string InspectionId { get; set; }
        public string PreviousInspectionId { get; set; }
        public bool IsLatestInspection { get; set; }
        public string Text2 { get; set; }
        public string ExposedGroup1 { get; set; }
        public int? ExposedGroup1Score { get; set; }
        public string ExposedGroup2 { get; set; }
        public int? ExposedGroup2Score { get; set; }
        public string ExposedGroup3 { get; set; }
        public int? ExposedGroup3Score { get; set; }
        public string Uprn { get; set; }
        public string OverAllAnalysisResult { get; set; }
        public string OverAllAnalysisResultScore { get; set; }
        public string RecommendationAction1 { get; set; }
        public string RecommendationPriority1 { get; set; }
        public string RecommendedBy1 { get; set; }
        public string RecommendationAction2 { get; set; }
        public string RecommendationPriority2 { get; set; }
        public string RecommendedBy2 { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? DateOfModification { get; set; }
        public DateTime DateOfCreation { get; set; }
        public bool IsApproved { get; set; }
	}
}
